print('Hello World!')
print('What is your name?')
myName=input()
print("It\'s good to meet you, "+myName)
print("The lenght of your name is: "+ str(len(myName)))
print("What is your age?")
age=int(input())
print("You will be "+str(age+2)+" in two years.")
